pipeline {
    agent any
    parameters {
        string(name: 'app_name', description: 'The name of the app to be created')
        string(name: 'git_email', description: 'The email for the git repo')
        string(name: 'git_user', description: 'The name of the username for the git repo')
        string(name: 'git_password', description: 'The name of the password for the git repo')
        string(name: 'jenkins_job_name', description: 'The name of the jenkins job')
        string(name: 'jenkins_job_parameters', description: 'The parameters for the jenkins job seperated by commas')
    }
    stages {
        stage('Setup App Name') {
            steps {
               dir("java-kubernetes/app"){
                  sh 'sed -i "s/@app_name@/$app_name/g" pom.xml'
               }
               dir("java-kubernetes/deploy/config"){
                  sh 'sed -i "s/@app_name@/$app_name/g" app.json'
               }
            }
        }
        stage('Setup Git Repository') {
           steps {
              sh 'curl -u \\"$git_user:$git_password\\" https://api.github.com/user/repos -d \\"{\\"name\\":"\\'+\\"app_name\\"+'\\"}\\"'
              sh 'git config --global user.email "$git_email"'
              sh 'git config --global user.name "$git_user"'
              sh 'echo "# $app_name" >> README.md'
              sh 'git init'
              sh 'git add README.md'
              sh 'git add java-kubernetes/app'
              sh 'git add java-kubernetes/deploy'
              sh 'git add java-kubernetes/infra'
              sh 'git add java-kubernetes/jenkins'
              sh 'git commit -m "add of project"'
              sh 'git remote set-url origin https://$git_user:$git_password@github.com/kriad85/$app_name.git'
              sh 'git push origin master'
           }
        }
    }
}
