pipeline {
    agent any
    parameters {
        string(name: 'app_name', description: 'The name of the app to be created')
        string(name: 'app_port', description: 'The port of the app to be exposed')
        string(name: 'replica_number', description: 'The port of the app to be exposed')
        string(name: 'image_registry', description: 'The port of the app to be exposed')
        string(name: 'service_type', description: 'The type of the service to be exposed')
        string(name: 'git_email', description: 'The email for the git repo')
        string(name: 'git_user', description: 'The name of the username for the git repo')
        string(name: 'git_password', description: 'The name of the password for the git repo')
        string(name: 'jenkins_job_name', description: 'The name of the jenkins job')
        string(name: 'jenkins_job_parameters', description: 'The parameters for the jenkins job seperated by commas')
    }
    stages {
        stage('Setup Application Parameters') {
            steps {
               dir("java-kubernetes/app"){
                  sh 'sed -i "s/@app_name@/$app_name/g" pom.xml'
               }
               dir("java-kubernetes/app/src/main/resources"){
                  sh 'sed -i "s/@app_port@/$app_port/g" application.properties'
               }
               dir("java-kubernetes/deploy/config"){
                  sh 'sed -i "s/@app_name@/$app_name/g" app.json'
                  sh 'sed -i "s/@deployment_name@/$app_name-deployment/g" app.json'
                  sh 'sed -i "s/@replica_number@/$replica_number/g" app.json'
                  sh 'sed -i "s/@image_name@/$image_registry/$app_name/g" app.json'
                  sh 'sed -i "s/@build_number@/1/g" app.json'
                  sh 'sed -i "s/@container_port@/$app_port/g" app.json'
                  sh 'sed -i "s/@service_name@/$app_name$-service/g" app.json'
                  sh 'sed -i "s/@service_type@/$service_type/g" app.json'
                  sh 'sed -i "s/@service_port@/$app_port/g" app.json'
                  sh 'sed -i "s/@service_protocol@/TCP/g" app.json'
               }
            }
        }
        stage('Setup Git Repository') {
           steps {
              dir("java-kubernetes"){
                 sh 'chmod +x create_repo.sh'
                 sh 'sed -i "s/@git_user@/$git_user/g" create_repo.sh'
                 sh 'sed -i "s/@git_password@/$git_password/g" create_repo.sh'
                 sh 'sed -i "s/@app_name@/$app_name/g" create_repo.sh'
                 sh './create_repo.sh'
                 sh 'git config --global user.email "$git_email"'
                 sh 'git config --global user.name "$git_user"'
                 sh 'echo "# $app_name" >> README.md'
                 sh 'git init'
                 sh 'git remote set-url origin https://$git_user:$git_password@github.com/kriad85/$app_name.git'
                 sh 'git add README.md'
                 sh 'git add app'
                 sh 'git add deploy'
                 sh 'git add infra'
                 sh 'git add jenkins'
                 sh 'git commit -m "add of project"'
                 sh 'git push origin master'
              }
           }
        }
        stage('Setup Jenkins Job') {
           steps {
               build job: 'Seed_JOB', parameters: [[$class: 'StringParameterValue', name: 'repo_name', value: "https://${params.git_user}:${params.git_password}@github.com/kriad85/${params.app_name}.git"],[$class: 'StringParameterValue', name: 'job', value: "${params.jenkins_job_name}"],[$class: 'StringParameterValue', name: 'job_parameters', value: "${params.jenkins_job_parameters}"]], propagate: true	
           }
        }
    }
}
